apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-datacenter
spec:
  template:
    metadata:
      name: countdown-datacenter
    spec:
      containers:
      - name: container-countdown-datacenter
        image: ubuntu:latest
        command: ["/bin/sh",  "-c", "for i in ten nine eight seven six five four three two one ; do echo $i ; done"]
      restartPolicy: Never
  
  We need to migrate CCBD beta databases to the new subscription. There is a microsoft article that you may be familiar with, that walks you through the process using native sql queries  https://docs.microsoft.com/en-us/azure/azure-sql/database/database-copy?tabs=azure-powershell&view=azuresql#copy-to-a-different-subscription. As you can see the query will require us to create an account in both the source and destination DBs. We wanted to run this by you and get your approval before we proceed with the migration.